---
title: "Homework 1"
author: "Mia Isaacs"
date: "2024-09-19"
output: github_document
---

# load library and dataset

```{r}
library(tidyverse)

data("penguins", package = "palmerpenguins")
```

# describe dataset

```{r}
variable_names <- colnames(penguins)
print(variable_names)

nrow(penguins)
ncol(penguins)
```

# find mean flipper length

```{r}
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

# scatter plot of flipper length vs. bill length

```{r}
scatterplot <- ggplot(penguins, aes(
  x = bill_length_mm, 
  y = flipper_length_mm,
  color = species)) +
  geom_point()

ggsave("bill_vs_flipper.png", scatterplot)
```

# create data frame

```{r}
data_frame = tibble(
  random_sample = rnorm(10),
  log_vec = rnorm(10) > 0,
  char_vec = sample(LETTERS, 10),
  fac_vec = factor(sample(c("A", "B", "C"), 10, replace = TRUE))
)

view(data_frame)
```

# take mean of each variable

```{r}
mean_random_sample <- data_frame %>% pull(random_sample) %>% mean()

mean_log_vec <- data_frame %>% pull(log_vec) %>% mean()

mean_char_vec <- data_frame %>% pull(char_vec) %>% mean()

mean_fac_vec <- data_frame %>% pull(fac_vec) %>% mean()
```

# convert to numeric variables

```{r}
numeric_log_vec <- data_frame %>% pull(log_vec) %>% as.numeric()

numeric_char_vec <- data_frame %>% pull(char_vec) %>% as.numeric()

numeric_fac_vec <- data_frame %>% pull(fac_vec) %>% as.numeric()
```




